name: asf-tools
channels:
  - conda-forge
  # - esri  # windows only
  - nodefaults
dependencies:
  - python>=3.8
  - pip
  # For packaging, and testing
  # - arcpy  # windows only
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - astropy
  - fiona
  - gdal>=3.3
  - numpy
  - pysheds
  - rasterio
  - scikit-fuzzy
  - scikit-image
  - shapely
  - pip:
    # for packaging and testing
    - s3pypi
    - gdal-utils
